name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            ./gradlew.bat clean build
          else
            ./gradlew clean build
          fi